[project]
name = "classy_foundry"
version = "0.0.0"
description = "A graphical user interface for classy_blocks python library"
readme = "README.md"
license = "MIT"
keywords = ["classy_foundry", "classy_blocks", "GUI", "OpenFOAM", "blockMesh"]
authors = [{ name = "Nejc Jurkovic", email = "nejc.jurkovic@proton.me" }]
requires-python = ">=3.9"
dependencies = ["polyscope", "classy_blocks"]

[project.urls]
"Homepage" = "https://github.com/damogranlabs/classy_foundry"
# "Tutorials" = "https://damogranlabs.com/category/classy_foundry"
# "Bug Tracker" = "https://github.com/damogranlabs/classy_foundry/issues"
# "Contributing" = "https://github.com/damogranlabs/classy_foundry/blob/master/CONTRIBUTING.md"

[project.optional-dependencies]
dev = ["pytest", "parameterized", "ruff~=0.9", "mypy~=1.2", "pre-commit"]

[build-system]
requires = ["setuptools >= 80.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py39"
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "YTT", "B", "A", "ARG", "RUF"]

[[tool.mypy.overrides]]
module = "scipy,scipy.*,parameterized.*,polyscope.*"
ignore_missing_imports = true


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
